name: Trigger Python Scripts on New Files

on:
  push:
    paths:
      - 'data_ingestion/**/*'       # Monitor the GCP directory and its subdirectories
      - 'configs/**/*'              # Monitor the SQL directory and its subdirectories

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Set up GCP authentication
      - name: Authenticate with GCP
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 --decode > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp-key.json"

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Identify new files and run corresponding Python scripts
      - name: Identify and Process New Files
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Fetch the list of new/changed files
          NEW_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'data_ingestion/**/*' 'configs/**/*')
          
          if [ -z "$NEW_FILES" ]; then
            echo "No new or modified files to process."
            exit 0
          fi

          echo "Processing the following new files:"
          echo "$NEW_FILES"

          for FILE in $NEW_FILES; do
            echo "Running script for $FILE..."
            python path/to/your_script.py --file $FILE
          done
