name: Data Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Authenticate with Google Cloud (Secure Method)
        uses: GoogleCloudPlatform/github-action-credentials@v0.1.1
        with:
          serviceAccountKey: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Data Ingestion Scripts
        run: |
          for script in data_ingestion/*.py; do
            echo "Running $script"
            python "$script"
          done

      - name: Test Data Pipeline (Optional)
        run: |
          pytest tests/

      - name: Deploy to Production (Optional)
        run: |
          # Add deployment steps here