name: CI/CD Pipeline for GCP Python Scripts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  execute-run-scripts:
    name: Execute All GCP Python Scripts Ending with run.py
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute All Python Scripts Ending with run.py
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        # Save the GCP service account key
        echo "$SERVICE_ACCOUNT_KEY" > service-account-key.json

        # Set GOOGLE_APPLICATION_CREDENTIALS for GCP authentication
        export GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json

        # Find and execute all Python scripts ending with 'run.py'
        find . -type f -name "*run.py" -print0 | while IFS= read -r -d '' script; do
          echo "Executing $script..."
          python "$script"
        done

    - name: Clean Up
      run: |
        # Remove sensitive files
        rm -f service-account-key.json
