name: Trigger Python Scripts on Any Change

on:
  push:
    branches:
      - main

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Authenticate with GCP
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" | base64 --decode > gcp-key.json
          ls -l gcp-key.json  # Debugging: Check if the key file exists
          cat gcp-key.json    # Debugging: Check the contents (remove this in production!)
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp-key.json"

          # Optional: Use gcloud to authenticate
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project [YOUR_PROJECT_ID]

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Identify and Process Python Scripts
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          if git cat-file -e ${{ github.event.before }} 2>/dev/null; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.py')
          else
            CHANGED_FILES=$(git ls-files '*.py')
          fi
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Python scripts to process."
            exit 0
          fi

          for FILE in $CHANGED_FILES; do
            echo "Running script: $FILE"
            python "$FILE"
          done
