name: GCP Python Script Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Authenticate to GCP
        uses: GoogleCloudPlatform/github-action-credentials@v0.1.1
        with:
          serviceAccountKey: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.PROJECT_ID }}
      - name: Run Python Script
        run: python your_script.py